name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - master
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print hlwrld
        run: echo "Hello world"
        
      - name: Git clone repo
        uses: actions/checkout@v1
